version: "3.8"

services:
  nodejs:
    container_name: nodejs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my_network


networks:
  my_network:
    external: true
      
    
