name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: [self-hosted, my-runner]  # Use your self-hosted runner with a specific label

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker images
      run: docker compose build

  deploy:
    runs-on: [self-hosted, my-runner]  # Use your self-hosted runner with a specific label
    needs: build  # Ensure deploy runs after build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy with Docker Compose
      run: docker compose up -d
