name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  copy:
    runs-on: self-hosted 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Rsync code to remote server
      run: |
        rsync -ravz ./ /home/anisha/nodeja-app

    - name: Set correct permissions on the server
      run: |
        sudo chown -R anisha:anisha /home/anisha/nodeja-app
        sudo chmod -R 755 /home/anisha/nodeja-app

  build:
    runs-on: self-hosted  
    needs: copy 

    steps:
    - name: Build Docker images
      run: |
        cd /home/anisha/nodeja-app
        sudo docker-compose build

  deploy:
    runs-on: self-hosted   
    needs: build  

    steps:
    - name: Deploy with Docker Compose
      run: |
        cd /home/anisha/nodeja-app
        sudo docker-compose up -d






